# Generated by Django 2.2.1 on 2019-05-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
        ('jobs', '0003_auto_20190515_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to='contributors.Contributor'),
        ),
        migrations.AddField(
            model_name='job',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
