# Generated by Django 2.2.1 on 2019-05-15 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward', to='rewards.Reward')),
            ],
        ),
    ]
